### ISSUE TITLE
Gauge doesn't support float

### ISSUE THREAD

**Issue by ghost** [lirsacc/statsd_client_python#1]
Hi,

I'm trying to migrate from https://github.com/jsocol/pystatsd to this, mainly for typing. It looks like `delta` is `is_update`, so that's working fine.

However, I have a handful of gauges that are floats. Not sure I need float precision, but would float support be worthwhile?

The type should be `Union[int, float]` in that case. `from typing import Union`.

I think Python 3.9, or maybe 3.10, has a handy new union type syntax, though.

Thank you!

**Comment by lirsacc** [comment]
Sorry this took a while @sometato.

I'd not used floats for gauge before but from a quick search it looks well supported by statsd servers (although not all) so I don't see any reason not to open up the type.

 I've [changed the types](https://github.com/lirsacc/statsd_client_python/commit/43f968e4b35337e640af4e5a33b2727fa569305e) and released 0.3.0 which includes the changes.

**Comment by ghost** [comment]
Thank you! I appreciate it.
