### ISSUE TITLE
py.typed no longer present

### ISSUE THREAD

**Issue by hhartzer** [lirsacc/statsd_client_python#3]
Hi!

Going from 0.3.0 to 0.5.0, I'm now getting errors with `mypy`. I think this is because the package is no longer including py.typed.

This might be because of this commit, changing `include_package_data`, but I may be mistaken.

https://github.com/lirsacc/statsd_client_python/commit/e41340b38b16328de340bab5c227327f7ddf3ffe

Thanks!

**Comment by lirsacc** [comment]
Just acknowledging I've seen this - I'll probably have time to look into fixing this over the weekend. 

Thanks for reporting this @hhartzer!

**Comment by lirsacc** [comment]
This should be fixed in [0.6.1](https://pypi.org/project/statsd-python/0.6.1/) (got a bit mixed up into updating packaging and wrongly thought I'd fixed it in 0.6.0).

There should no other changes to the code.

**Comment by hhartzer** [comment]
That works great! Thank you so much!
